services:
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    networks:
      - ecommerce
  admin:
    build: admin
    ports:
      - "5174:5174"
    networks:
      - ecommerce
  backend:
    build: backend
    ports:
      - "4000:4000"
    networks:
      - ecommerce
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - ecommerce
    volumes:
      - ./mongo-data:/data/db

networks:
  ecommerce:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    